# Generated by Django 4.0.2 on 2022-04-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='room',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
